spring:
  application:
    name: spring-keycloak
  datasource:
    jpa:
      hibernate:
        ddl-auto: update
    url: <change_me>
    username: <change_me>
    password: <change_me>
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <change_me>
          jwk-set-uri: <change_me>
keycloak:
  realm: <change_me>
  auth-server-url: <change_me>
